name: Push essentials package to artifacts (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt update
          sudo apt purge dotnet*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev dotnet-sdk-6.0
        
      - name: Initialize offline package
        run: |
          chmod +x initializeoffline.sh
          ./initializeoffline.sh --generate-essentials-archive
        
      - name: Upload essentials to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Essentials
          path: |
            Essentials.tar.xz
            offline/.dotnet
          
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
