name: Push essentials package to artifacts (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo add-apt-repository ppa:eofla/msbuild
          sudo apt update
          sudo apt purge mono-roslyn msbuild-sdkresolver msbuild-libhostfxr
          sudo apt purge mono-*
          sudo apt autoremove
<<<<<<< HEAD
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev msbuild msbuild-roslyn mono-devel mono-vbnc libmono-microsoft-visualbasic10.0-cil inxi libcpanel-json-xs-perl libmono-2.0-1 libmono-profiler mono-4.0-service
=======
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev msbuild msbuild-roslyn mono-vbnc libmono-microsoft-visualbasic10.0-cil inxi libcpanel-json-xs-perl
>>>>>>> servicing
        
      - name: Initialize offline package
        run: |
          chmod +x initializeoffline.sh
          ./initializeoffline.sh --generate-essentials-archive
        
      - name: Upload essentials to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Essentials
          path: |
            Essentials.tar.xz
            offline/.dotnet
          
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
