name: Push to PPA (Debug level 2 for validation)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo add-apt-repository ppa:eofla/msbuild
          sudo apt update
          sudo apt purge mono-roslyn msbuild-sdkresolver msbuild-libhostfxr
          sudo apt purge mono-*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev msbuild msbuild-roslyn mono-vbnc libmono-microsoft-visualbasic10.0-cil inxi libcpanel-json-xs-perl devscripts debhelper-compat dput libmono-2.0-1 libmono-profiler mono-4.0-service
        
      - name: Initialize offline package
        run: |
          chmod +x initializeoffline.sh
          ./initializeoffline.sh
          
      - name: Setup tmate session for validation
        uses: mxschmitt/action-tmate@v3
        
      - name: Make original package
        run: |
          mv debian ..
          mv .github ..
          tar cfv ../kernel-simulator_0.0.17.1.orig.tar .
          xz -9 ../kernel-simulator_0.0.17.1.orig.tar
          mv ../debian .

      - name: Build source package
        run: debuild -S -sa
        
      - name: Push to Launchpad
        run: dput ppa:eofla/kernel-sim ../kernel-simulator_0.0.17.1_source.changes
        
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
