name: Push to PPA (amend with original source) (Debug level 2 for validation)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo add-apt-repository ppa:eofla/msbuild
          sudo apt update
          sudo apt purge mono-roslyn msbuild-sdkresolver msbuild-libhostfxr
          sudo apt purge mono-*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev msbuild msbuild-roslyn mono-vbnc libmono-microsoft-visualbasic10.0-cil inxi libcpanel-json-xs-perl devscripts debhelper-compat dput libmono-2.0-1 libmono-profiler mono-4.0-service
        
      - name: Download original source
        run: |
          wget --output-document=../kernel-simulator_0.0.22.2.orig.tar.xz https://launchpad.net/~eofla/+archive/ubuntu/kernel-sim/+sourcefiles/kernel-simulator/0.0.22.2/kernel-simulator_0.0.22.2.orig.tar.xz
          tar xf ../kernel-simulator_0.0.22.2.orig.tar.xz ./Kernel-Simulator
          mv .github ..

      - name: Build source package
        run: debuild -S
          
      - name: Setup tmate session for validation
        uses: mxschmitt/action-tmate@v3
        
      - name: Push to Launchpad
        run: dput ppa:eofla/kernel-sim ../kernel-simulator_0.0.22.2-0ppa1_source.changes
          
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
