name: Test building (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo add-apt-repository ppa:eofla/msbuild
          sudo apt update
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev msbuild msbuild-roslyn mono-devel mono-vbnc libmono-microsoft-visualbasic10.0-cil inxi libcpanel-json-xs-perl
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
          chmod +x initializeoffline.sh
          ./initializeoffline.sh
        
      - name: Try to build
        run: |
          cd Kernel-Simulator
          sudo ip netns exec no-net msbuild -t:restore
          sudo ip netns exec no-net msbuild
          
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
