name: Test building (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt purge dotnet*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev dotnet-sdk-6.0 devscripts debhelper-compat dput
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
          chmod +x initializeoffline.sh
          ./initializeoffline.sh
        
      - name: Try to build
        run: |
          cd Kernel-Simulator
          sudo ip netns exec no-net msbuild Nitrocid.sln -t:restore
          sudo ip netns exec no-net msbuild Nitrocid.sln -p:Configuration=Release
          
      - name: Setup tmate session for debug failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
